version: '3.10'

volumes:
  postgres_data:
  backups:

services:
  api:
    container_name: kan_api
    restart: always
    build:
      context: .
    command:
          sh -c "python manage.py wait_for_db &&
                 python manage.py migrate &&
                 python manage.py create_statuses &&
                 python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/kan
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-3a_)xg#or1ttpiyn8etg=&q&#&lkwx8l&y_$$(h#hvgkp1agvjo
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0 192.168.101.186 [::1]
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=kan_db
      - DB_ENGINE=django.db.backends.postgresql
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - db
      - redis
  db:
    container_name: kan_db
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ${HOME}/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=kan_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
  redis:
    container_name: kan_redis
    image: redis:7.2.2-alpine
  celery:
    container_name: kan_celery
    build: .
    command: celery -A kanban worker -l info
    volumes:
      - .:/kan
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-3a_)xg#or1ttpiyn8etg=&q&#&lkwx8l&y_$$(h#hvgkp1agvjo
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0 192.168.101.186 [::1]
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=kan_db
      - DB_ENGINE=django.db.backends.postgresql
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
  celery-beat:
    container_name: kan_celery_beat
    build: .
    command: celery -A kanban beat -l info
    volumes:
      - .:/kan
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-3a_)xg#or1ttpiyn8etg=&q&#&lkwx8l&y_$$(h#hvgkp1agvjo
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0 192.168.101.186 [::1]
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=kan_db
      - DB_ENGINE=django.db.backends.postgresql
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
  pgbackups:
    container_name: kan_backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ${HOME}/kan_db_backups:/backups
    links:
      - db:db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=kan_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
#      - SCHEDULE=@every 1h00m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81
