version: '3.10'

volumes:
  postgres_data:
  kan_db_backups:
  static_volume:

services:
  api:
    container_name: kan_api
    restart: always
    image: kan-two.gis:5000/kan_api:latest
    command:
          sh -c "python manage.py wait_for_db &&
                 python manage.py collectstatic --clear --noinput &&
                 python manage.py migrate &&
                 gunicorn kanban.wsgi:application --bind 0.0.0.0:8080 --workers 3 --access-logfile /var/log/access.log --forwarded-allow-ips="*" --error-logfile /var/log/error.log"
    volumes:
      - static_volume:/kan/staticfiles
    env_file:
      - envs/env_prod
    depends_on:
      - db
      - redis

  front:
    container_name: kan_front
    image: kan-two.gis:5000/kan-front:latest
    env_file:
      - envs/env_prod
    ports:
     - "80:80"
    restart: always
    links:
     - api

  nginx:
    container_name: kan_nginx
    image: kan-two.gis:5000/nginx:latest
    restart: always
    ports:
      - "8000:80"
    volumes:
      - static_volume:/var/www/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    command: ["nginx", "-g", "daemon off;"]

  db:
    container_name: kan_db
    image: kan-two.gis:5000/postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ${HOME}/postgres_data:/var/lib/postgresql/data/
    env_file:
      - envs/env_prod

  redis:
    container_name: kan_redis
    image: kan-two.gis:5000/redis:latest
    restart: always

  celery:
    container_name: kan_celery
    image: kan-two.gis:5000/kan_celery:latest
    command: celery -A kanban worker -l info
    restart: always
    env_file:
      - envs/env_prod
    depends_on:
      - redis

  celery-beat:
    container_name: kan_celery_beat
    image: kan-two.gis:5000/kan_celery-beat:latest
    command: celery -A kanban beat -l info
    restart: always
    env_file:
      - envs/env_prod
    depends_on:
      - redis

  pgbackups:
    container_name: kan_backup
    image: kan-two.gis:5000/prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ${HOME}/kan_db_backups:/backups
    links:
      - db:db
    depends_on:
      - db
    env_file:
      - envs/env_prod
    environment:
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81
