# Generated by Django 4.2.1 on 2023-12-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EDITOR', 'Виконавець'), ('CORRECTOR', 'Коректор'), ('VERIFIER', 'Контролер')], default='EDITOR', max_length=32, verbose_name='Роль'),
        ),
    ]
