# Generated by Django 4.2.1 on 2023-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetracker",
            name="task_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WAITING", "Очікування"),
                    ("IN_PROGRESS", "В роботі"),
                    ("STOPPED", "Призупинено"),
                    ("DONE", "Завершено"),
                    ("CORRECTING", "Корректура"),
                    ("CORRECTING_QUEUE", "Черга корректури"),
                    ("OTK", "ОТК"),
                    ("OTK_QUEUE", "Черга ОТК"),
                ],
                default="WAITING",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
