# Generated by Django 4.2.1 on 2023-08-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_user_is_superuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="department",
            name="ordering",
            field=models.PositiveIntegerField(
                null=True, unique=True, verbose_name="Номер в черзі відображення"
            ),
            preserve_default=False,
        ),
    ]
