# Generated by Django 4.2.1 on 2023-06-29 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_timetracker_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetracker",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_tracker_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Виконавець",
            ),
        ),
    ]
