# Generated by Django 4.2.1 on 2023-10-15 13:40

import api.fields
import api.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_task_involved_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=api.fields.RangeIntegerField(
                default=3,
                validators=[
                    api.validators.KanMinValueValidator(3),
                    api.validators.KanMaxValueValidator(10),
                ],
                verbose_name="Категорія складності",
            ),
        ),
    ]
