# Generated by Django 4.2.1 on 2023-09-01 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_comment_options_department_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["ordering"]},
        ),
    ]
