# Generated by Django 4.2.1 on 2024-01-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_sheet', '0001_initial'),
        ('api', '0004_alter_task_scale_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='map_sheet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='map_sheet.mapsheet', verbose_name='Аркуш'),
        ),
    ]
