# Generated by Django 4.2.1 on 2023-09-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_department_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="scale",
            field=models.CharField(
                choices=[
                    (25, "1:25 000"),
                    (50, "1:50 000"),
                    (100, "1:100 000"),
                    (200, "1:200 000"),
                    (500, "1:500 000"),
                ],
                default=50,
                max_length=50,
                verbose_name="Масштаб",
            ),
        ),
    ]
