# Generated by Django 4.2.1 on 2023-09-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_task_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="year",
            field=models.PositiveIntegerField(default=2023),
        ),
    ]
