# Generated by Django 4.2.1 on 2023-09-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_task_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="primary_department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="task_primary_departments",
                to="api.department",
                verbose_name="Початковий відділ",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="scale",
            field=models.IntegerField(
                choices=[
                    (25, "1:25 000"),
                    (50, "1:50 000"),
                    (100, "1:100 000"),
                    (200, "1:200 000"),
                    (500, "1:500 000"),
                ],
                default=50,
                verbose_name="Масштаб",
            ),
        ),
    ]
