# Generated by Django 4.2.1 on 2023-09-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_task_primary_department_alter_task_scale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.RemoveField(
            model_name='department',
            name='ordering',
        ),
    ]
