# Generated by Django 4.2.1 on 2023-09-14 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_department_options_remove_department_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Статус"
                    ),
                ),
                (
                    "translation",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Переклад"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["is_verifier", "id"]},
        ),
        migrations.AddField(
            model_name="department",
            name="status",
            field=models.ManyToManyField(
                related_name="department_status", to="api.status", verbose_name="Статус"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="task_status",
                to="api.status",
                verbose_name="Статус",
            ),
        ),
    ]
