# Generated by Django 4.2.1 on 2023-09-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_status_alter_department_options_department_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetracker",
            name="task_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time_tracker_task_status",
                to="api.status",
                verbose_name="Статус задачі",
            ),
        ),
    ]
