# Generated by Django 4.2.1 on 2024-02-12 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsheet',
            name='year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2029)], verbose_name='Рік'),
        ),
    ]
